Repository openstudiocoalition/OpenStudioApplication, pull requests merged in 2021-05, with the labels that each got.

#348 Fix #346 - avoid copying openstudiolib twice
  CMakeLists.txt
Labels: Enhancement Request, component - Installer/Platform :package:

#346 Fix #345 - Missing libs in Ubuntu installer
  .github/workflows/app_build.yml
Labels: component - Installer/Platform :package:, severity - Blocker :no_entry_sign:

#343 Rename the installers for clarity
  CMake/TargetArch.cmake
  CMakeLists.txt
Labels: component - Installer/Platform :package:

#350 Fix #349 - Remove Annoying messages in console about QWebEngine not finding its resources/translations by correctly setting them up
  src/openstudio_app/CMakeLists.txt
  src/openstudio_app/main.cpp
  src/openstudio_app/qt.conf
Labels: component - Installer/Platform :package:

#361 Fix #219 - Add AirLoopHVAC "design return airflow fraction" to the App enStudioApplication and adjust OpenStudioPolicy to hide splitter/mixer
  src/openstudio_lib/library/OpenStudioPolicy.xml
Labels: component - UI, severity - Minor Bug :baby_chick:

#362 Fix #219 VRF from hvac_library makes E+ Fatal Out
  src/openstudio_app/Resources/default/hvac_library.osm
Labels: component - Backend, severity - Normal Bug :bug:

#363 Fix #356 - Handle launching the app from terminal from any location based on adding OpenStudioApp to path
  src/openstudio_app/CMakeLists.txt
  src/openstudio_app/main.cpp
  src/utilities/OpenStudioApplicationPathHelpers.cxx.in
Labels: Platform - Ubuntu, component - Backend, severity - Major Bug :boom:

#367 366 geometry editor map
  CMakeLists.txt
  src/openstudio_app/CMakeLists.txt
  src/openstudio_lib/OSWebEnginePage.cpp
  src/openstudio_lib/OSWebEnginePage.hpp
Labels: component - Geometry Editor

#370 Fix #305 - Add new Fan:ComponentModel to the OpenStudioApplication
  src/openstudio_app/Resources/default/hvac_library.osm
  src/openstudio_lib/IconLibrary.cpp
  src/openstudio_lib/MainRightColumnController.cpp
  src/openstudio_lib/images/fan_componentmodel.png
  src/openstudio_lib/images/mini_icons/fan_componentmodel.png
  src/openstudio_lib/library/OpenStudioPolicy.xml
  src/openstudio_lib/openstudio.qrc
  src/openstudio_lib/test/IconLibrary_GTest.cpp
Labels: Added To Library, Enhancement Request, component - Backend

#368 Misc fixes: don't orphan CLI when exiting the App to prevent a crash report on mac
  src/openstudio_app/OpenStudioApp.cpp
  src/openstudio_lib/GeometryPreviewView.cpp
  src/openstudio_lib/openstudio.qrc
Labels: Platform - Mac, Platform - Ubuntu, Platform - Windows, component - Backend
