Repository openstudiocoalition/OpenStudioApplication, pull requests merged in 2024-09, with the labels that each got.

#732 Fix a race condition during CPack packaging when creating symlink on Apple
  src/openstudio_app/CMakeLists.txt
Labels: Developer Issue :nerd_face:

#730 Fix #708 - Improve SetpointManager views: support more types, add plots where applicable, and support PlantLoop
  .github/workflows/app_build.yml
  CMakeLists.txt
  src/openstudio_lib/HVACSystemsController.cpp
  src/openstudio_lib/HVACSystemsController.hpp
  src/openstudio_lib/HVACSystemsView.cpp
  src/openstudio_lib/HVACSystemsView.hpp
Labels: Enhancement Request, component - UI

#733 Fix #671 - Mark Python Measures as in Error if use classic CLI to run the simulation
  src/shared_gui_components/LocalLibraryController.cpp
  src/shared_gui_components/WorkflowController.cpp
Labels: component - UI

#737 Fix resources install
  CMakeLists.txt
  src/openstudio_app/CMakeLists.txt
Labels: severity - Blocker :no_entry_sign:, component - Installer/Platform :package:

#740 Fix #739 - Issues with Ubuntu 24.04: unmet apt dependencies, icon not showing
  CMakeLists.txt
  debian/openstudioapp.desktop
  debian/x-openstudio.xml
Labels: Enhancement Request, component - Installer/Platform :package:, Platform - Ubuntu

#748 Fix #747 - crash shoebox
  src/openstudio_app/OpenStudioApp.cpp
  src/shared_gui_components/LocalLibraryController.cpp
  src/shared_gui_components/WorkflowController.cpp
Labels: severity - Normal Bug :bug:, component - Backend

#749 Improve installer
  CMakeLists.txt
Labels: Enhancement Request, component - Installer/Platform :package:

#754 Add an Ubuntu-2404 runner
  .github/workflows/app_build.yml
  FindOpenStudioSDK.cmake
Labels: Developer Issue :nerd_face:, component - Installer/Platform :package:
