Repository openstudiocoalition/OpenStudioApplication, pull requests merged in 2025-07, with the labels that each got.

#791 Fix #153 - Allow users to specifically import 99%,99.6%, 0.4%,1% and 2% annual design days
  .github/workflows/app_build.yml
  src/openstudio_lib/CMakeLists.txt
  src/openstudio_lib/LocationTabView.cpp
  src/openstudio_lib/LocationTabView.hpp
  src/openstudio_lib/test/LocationTab_GTest.cpp
  src/shared_gui_components/OSCellWrapper.cpp
  src/shared_gui_components/OSCellWrapper.hpp
  src/shared_gui_components/OSObjectSelector.cpp
  translations/OpenStudioApp_ar.ts
  translations/OpenStudioApp_ca.ts
  translations/OpenStudioApp_de.ts
  translations/OpenStudioApp_el.ts
  translations/OpenStudioApp_es.ts
  translations/OpenStudioApp_fa.ts
  translations/OpenStudioApp_fr.ts
  translations/OpenStudioApp_he.ts
  translations/OpenStudioApp_hi.ts
  translations/OpenStudioApp_it.ts
  translations/OpenStudioApp_ja.ts
  translations/OpenStudioApp_pl.ts
  translations/OpenStudioApp_vi.ts
  translations/OpenStudioApp_zh_CN.ts
Labels: Enhancement Request, component - UI

#820 Fix #816 - Add ZoneHVAC:EvaporativeCoolerUnit to OS App
  src/openstudio_app/Resources/default/hvac_library.osm
  src/openstudio_lib/IconLibrary.cpp
  src/openstudio_lib/MainRightColumnController.cpp
  src/openstudio_lib/images/mini_icons/zonehvac_evaporativecoolerunit.png
  src/openstudio_lib/images/mini_icons/zonehvac_evaporativecoolerunit@2x.png
  src/openstudio_lib/images/zonehvac_evaporativecoolerunit.png
  src/openstudio_lib/images/zonehvac_evaporativecoolerunit@2x.png
  src/openstudio_lib/library/OpenStudioPolicy.xml
  src/openstudio_lib/openstudio.qrc
  src/openstudio_lib/test/IconLibrary_GTest.cpp
Labels: Enhancement Request, component - UI, component - Backend, Added To Library

#824 Revert changes to BuildingComponentDialogCentralWidget from PR #795
  src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp
  src/shared_gui_components/BuildingComponentDialogCentralWidget.hpp
Labels: Developer Issue :nerd_face:

#826 #825 - Expose Terrain, Elevation and Keep Site Location Information on the Site Tab
  src/openstudio_lib/LocationTabView.cpp
  src/openstudio_lib/LocationTabView.hpp
  src/shared_gui_components/Component.cpp
  src/shared_gui_components/OSComboBox.cpp
  src/shared_gui_components/OSComboBox.hpp
  src/shared_gui_components/OSQuantityEdit.cpp
  src/shared_gui_components/OSQuantityEdit.hpp
Labels: Enhancement Request, component - UI, component - Backend
